name: Java CI with Tests and Analysis

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GROUPGRUB_DB_URL: "jdbc:mysql://35.237.146.125:3306/groupgrubdb"
      GROUPGRUB_DB_USER: "root"
      GROUPGRUB_DB_PASSWORD: "dbuserdbuser"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Run Tests
        run: mvn test

      - name: Run Checkstyle and save Checkstyle Report
        run: mvn checkstyle:checkstyle > checkstyle-report.xml

      - name: Run Static Analysis and save Static Analysis Report
        run: mvn pmd:check > pmdresult.txt

      - name: Run Coverage Analysis and save Coverage Report
        run: mvn jacoco:prepare-agent test jacoco:report > target/site/jacoco/index.html
